---
- hosts: all
  become: true

  vars:
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- hosts: all
  become: true
  roles:
    - bootstrap
    - common

- hosts: web
  become: true
  roles:
    - web

- hosts: database
  become: true
  roles:
    - postgres

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/lab-app
    owner: root
    group: root
    mode: "0644"

- name: Enable lab nginx configuration
  file:
    src: /etc/nginx/sites-available/lab-app
    dest: /etc/nginx/sites-enabled/lab-app
    state: link

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted